spring:
  data:
    neo4j:
      database: neo4j
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
  elasticsearch:
    uris: localhost:9200

logging:
  level:
    org:
      neo4j:
        driver: DEBUG
    springframework:
      data:
        neo4j:
          core: DEBUG
          repository:
            query: DEBUG
